/* DO NOT EDIT THIS FILE */
var config =
    /* config object start */
{
    "facebookPermissions": "public_profile,user_friends,email",
    "googleAnalyticsTag": "GTM-MB6MXG",
    "googleClientId": "713042056852-vio2jnjfs89v7rnuirhm9pff7s3o0lqj.apps.googleusercontent.com",
    "googleAuthScope": "profile email",
    "authStorageToken": "contempo_auth_store",
    "userStorageToken": "contempo_user_store",
    "authLevels": {
        "none": "contempo_perm_none",
        "pending": "contempo_perm_pending",
        "authenticated": "contempo_perm_authenticated"
    },
    "routes": {
        "login": "/login",
        "explore": "/explore",
        "dashboard": "/dashboard",
        "default": "/",
        "recommended": "/recommended",
        "related": "/related/:id",
        "signup": "/signup",
        "saved": "/saved",
        "settings": "/settings",
        "trending": "/trending"
    },
    "shortlinkHostname": "http://qklnk.co/",
    "curTOSVersion": "1",
    "facebookAppId": "585424068290849",
    "apiUrl": "http://geordi.dev:3000",
    "debug": true,
    "legacyCSS": "/css/legacy.css",
    "legacyAppJS": "/js/legacy/app.js",
    "legacyDashboardJS": "/js/legacy/dashboard.js"
}    
/* config object end */
;

export default config;
